name: CI

# Controls when the workflow will run
on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  components: clippy
                  override: true
            - uses: Swatinem/rust-cache@v2

            - name: Install cargo-about
              run: cargo install --locked cargo-about

            # - uses: actions-rs/cargo@v1
            #   name: Unit test
            #   env:
            #       USE_PREBUILT_ASSETS: 1
            #       USE_PRECOMPILED_CPP_LOADER: 1
            #   with:
            #       token: ${{ secrets.GITHUB_TOKEN }}
            #       command: test

            - uses: actions-rs/clippy-check@v1
              name: Clippy check
              env:
                  USE_PREBUILT_ASSETS: 1
                  USE_PRECOMPILED_CPP_LOADER: 1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: -- -D warnings
